csmith-project/creduce

- clang_delta/RemoveUnusedFunction.cpp
When removing an unused function declaration (without body) the following semicolon should also be removed.
> Remove trailing semicolon for functions without body

- clang_delta/EmptyStructToInt.cpp
- clang_delta/EmptyStructToInt.h
- clang_delta/RemoveUnusedStructField.cpp
This pull request fixes an issue with the transformation remove-unused-field. When the last item of an initialiser list with a trailing comma had been removed the list was left only with the comma inside. While a trailing comma after the last element is allowed the list with only the comma is syntactically incorrect.
Further the transformation empty-struct-to-int is extended. This pull request changes the behaviour such that any initialiser list for the struct under change is replace with a zero constant to initialise the new int variable. Without these changes undefined behaviour is introduced in the case of an array, struct or union as last unused field in the struct under change. After the struct under change is turned into an int any variable with the old struct type would potentially …
> Improved transformations on structs

- clang_delta/ClassTemplateToClass.cpp
- clang_delta/InstantiateTemplateParam.cpp
- clang_delta/InstantiateTemplateTypeParamToInt.cpp
- clang_delta/LocalToGlobal.cpp
- clang_delta/ParamToGlobal.cpp
- clang_delta/ReduceClassTemplateParameter.cpp
- clang_delta/RemoveBaseClass.cpp
- clang_delta/RemoveCtorInitializer.cpp
- clang_delta/RemoveTrivialBaseTemplate.cpp
- clang_delta/RemoveUnresolvedBase.cpp
- clang_delta/RemoveUnusedFunction.cpp
- clang_delta/RemoveUnusedOuterClass.cpp
- clang_delta/RenameClass.cpp
- clang_delta/RenameFun.cpp
- clang_delta/ReplaceClassWithBaseTemplateSpec.cpp
- clang_delta/ReplaceDependentName.cpp
- clang_delta/ReplaceDependentTypedef.cpp
- clang_delta/ReplaceDerivedClass.cpp
- clang_delta/SimplifyDependentTypedef.cpp
- clang_delta/SimplifyNestedClass.cpp
- clang_delta/SimplifyRecursiveTemplateInstantiation.cpp
- clang_delta/TemplateArgToInt.cpp
- clang_delta/TemplateNonTypeArgToInt.cpp
- clang_delta/TransformationManager.cpp
- clang_delta/TransformationManager.h
This pull request disables some clang_delta transformations for OpenCL input files. For example, the param-to-global transformation does not work for OpenCL as there are no C-like globals.
> Disable some clang_delta transformations for OpenCL

- clang_delta/TransformationManager.cpp
- clang_delta/TransformationManager.h
This pull request adds automatic detection for OpenCL input. If the input file is assumed to contain OpenCL code the clang instance used by clang_delta is configured for OpenCL. Since clang does not know about the types defined in OpenCL and the functions the libclc headers have to be included. The path can be specified via an environment variable.
Further, the all *clang_delta* transformation are now considered as unsuccessful if any errors occurred during the parsing of the source code. I am not quite sure how useful this is but my intention was that if the creation of the AST goes wrong the transformations are likely to produce wrong code or do weird things.
Do you have any concerns about the changes?
> OpenCL support for clang_delta

- CMakeLists.txt
Appending the values seems to be a (or the) correct approach as suggested in the comment #72  for this issue.
> Append CMAKE_CXX_FLAGS instead of overwriting

- clang_delta/TransformationManager.cpp
- creduce/creduce.in
When reducing files that are not fully preprocessed clang_delta needs to know the where the included files can be found, and in the case of testing cross compilers the target triple needs to be changed. The least intrusive way of doin this is by environment variables.
> Set clang_delta include path and target triple using environment variables

- clang_delta/RenameFun.cpp
There was a mismatch in the RenameFun translation where functions
declared in included files were ignored when collecting information on
which functions to replace but not when performing the actual
replacement.
> Make RenameFun ignore functions declared in included files

- clang_delta/RenameClass.cpp
Detected by GCC's "logical-op" check:
RenameClass.cpp: In member function ‘bool RenameClass::isValidName(const string&)’:
RenameClass.cpp:163:23: warning: logical ‘or’ of collectively exhaustive tests is always true [-Wlogical-op]
return (((C >= 'A') || (C <= 'Z')) && !isReservedName(C));
~~~~~~~~~~~^~~~~~~~~~~~~
> Fix condition logic in RenameClass::isValidName

- clang_delta/ReplaceArrayAccessWithIndex.cpp
- clang_delta/ReplaceArrayAccessWithIndex.h
I added a copyright notice to the files. They are licenced under the same terms as the rest of creduce.
> Fix #99: Add missing copyright message

- clang_delta/CMakeLists.txt
Fix a linking problem that occured for us in the newest LLVM.
> fix linkage problems with newest llvm

- creduce/creduce.in
- creduce/pass_lines.pm
- The exitcode handling was incorrect since the last refactoring
- The grep tool has been replaced by a Perl loop as it is not available
on Windows
> Fix C-Reduce on Windows

- clang_delta/RenameCXXMethod.cpp
http://llvm.org/docs/doxygen/html/classllvm_1_1StringRef.html#ad977ad21e398b4cda9801dc8e86cf169
Can you verify that this fix looks right, Yang? Thanks!
> drop_front doesn't mutate the string but rather returns the new string:

- clang_delta/EmptyStructToInt.h
- clang_delta/ReduceArraySize.h
- clang_delta/RemoveArray.h
- clang_delta/RemovePointer.cpp
- clang_delta/RemovePointer.h
- clang_delta/RemoveUnusedOuterClass.cpp
- clang_delta/RemoveUnusedOuterClass.h
- clang_delta/ReplaceOneLevelTypedefType.h
- clang_delta/ReplaceUndefinedFunction.h
- clang_delta/UnionToStruct.h
For some transformations the order of the possible transformations within the test case is non-deterministic. This is because the instances are stored in maps or sets which are ordered by pointer values.
This PR replaces those maps and sets with ones that keep the insertion order.
For an example you can use the `compiler-crashes/00/small.cpp` test case.
```
clang_delta --transformation=empty-struct-to-int --counter=1 small.cpp
```
If you run it multiple times (without changing small.cpp in between) you will get different results for the transformed small.cpp because every time another empty struct is selected for `--counter=1`.
> Fix non-deterministic clang_delta transformations

- clang_delta/CMakeLists.txt
Link clang_delta against LLVMSupport in order to fix the following link
failure:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/clang_delta.dir/ReplaceArrayIndexVar.cpp.o: undefined reference to symbol '_ZN4llvm5APInt12initSlowCaseERKS0_'
/usr/lib64/libLLVMSupport.so.40: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
> [clang_delta] Link against LLVMSupport to fix missing APInt methods

- clang_delta/CMakeLists.txt
On Windows the clang dependencies require to link against `Version`.
> Fix build on Windows

- clang_delta/ExpressionDetector.cpp
Use clang::StringLiteral rather than relying on the using statement
since llvm::StringLiteral was introduced lately and made plain
'StringLiteral' ambiguous.
> clang_delta: Namespace-qualify clang::StringLiteral

- INSTALL
- clang_delta/CMakeLists.txt
If LLVM and Clang have not been installed into the same location it is
necessary to specify the include directory for the clang headers
separate from the LLVM include directory.
> Require package Clang for clang_delta

- creduce/creduce.in
Not trying to start a style flame war, but...
The mixed tabs and spaces was making indentation really funky in Emacs, and
since there was more spaces indenting than tabs, I moved everything over to
spaces.
> Replace tabs with spaces

- INSTALL
- creduce/creduce_utils.pm
Turns out sys::cpu was only used on platforms that aren't Linux or OS X. I can't imagine we have many users on those platforms. Just default to one core in that case since Sys::CPU seems to have died in CPAN. People can still override using a command line flag.
> stop using dead sys::cpu perl module

- creduce/creduce.in
I have a very old Linux kernel (2.6.32) here, which makes lscpu fail:
```
lscpu: failed to determine number of CPUs: /sys/devices/system/cpu/possible: No such file or directory
```
I don't mind specifying `--n` manually, but I don't want to see the error message when I do.
> Check number of CPUs only if --n wasn't specified

- clang_delta/ReduceArraySize.cpp
Hi all,
There is reused variable name issue found by Qihoo360 CodeSafe Team.
Since variable 'I' is already used as the iterator in for in line 108, in line 123, it is better to use another variable as the counter for the for loop.
Cheers
Qihoo360 CodeSafe Team
> Use a different name for the sub loop

- creduce/creduce.in
- creduce/pass_unifdef.pm
This adds a part to pass_unifdef that removes constant #if statements. The reordering is for the possibility that includes get nested under ifs.
> Add a pass to remove constant ifs

- creduce/CMakeLists.txt
- creduce/Makefile.am
- creduce/Makefile.in
- creduce/creduce.in
- creduce/pass_line_markers.pm
This is a pass that removes line markers in binary search chunks, since we get a lot of these and they often can't all be removed at once.
> Add pass for line markers

- creduce/pass_comments.pm
I noticed that the comments pass often doesn't work because of some edge cases where it tries to remove non-comments (e.g. strings with urls, or // ...*/... ). So I added an extra binary search pass that removes just c++ style comments. 
Removing cstyle comments seems a bit more tricky, so I didn't consider them here. It's might also contribute less to improving runtime, since they don't break up lines in topformflat like the c++ style comments do.
> binary search removal of c++ style comments

- clang_delta/CMakeLists.txt
- clang_delta/Makefile.am
- clang_delta/Makefile.in
The change is needed to link clang_delta with LLVM version 9.
> Link clang_delta only with -lclang-cpp (#193).

- creduce/creduce.in
This option allows the user to remove a specific pass without having to
re-enter the entire schedule.
> Add command line option for removing a specific pass from schedule

- clang_delta/RemoveBaseClass.cpp
Without the fix the opening brace of the base class's definition was copied to the derived class together with it's declarations. This resulted in invalid code. For instance
```
class B {
int a;
};
class D : B {
int c;
};
```
got transformed into
```
class D  {
int c;
{
int a;};
```
With the changes the result is
```
class D  {
int c;
int a;};
```
The same changes has also been made for C-Vise: https://github.com/marxin/cvise/blame/9f237d6619f08e85784e5356869f48f81678815f/clang_delta/RemoveBaseClass.cpp#L190
> [clang_delta] Fix offset in RemoveBaseClass pass

- CMakeLists.txt
- clang_delta/RemoveUnusedStructField.cpp
* A minor change to be compatible with LLVM >=17 as well as the older versions
- credit to @mizvekov for #264
* Avoid hardcoding C++ standard flag via "-std=XX"
- a newer version of LLVM requires newer C++ standards.
- based on the llvm version, use specific C++ standards and let cmake add an appropriate flag.
Otherwise, compiling the master branch with the latest LLVM ends with errors like the following:
```console
[  1%] Building CXX object clang_delta/CMakeFiles/clang_delta.dir/AggregateToScalar.cpp.o
cd /home/kumbhar/workarena/repos/external/creduce/build/clang_delta && /usr/bin/c++ -DHAVE_CONFIG_H -DNDEBUG -I/home/kumbhar/workarena/repos/external/creduce/build -I/home/kumbhar/workarena/repos/external/creduce/clang_delta -I/home/kumbhar/workarena/repos/bbp/spack_upstream/opt/spack/linu …
```
> Fix hardcoded C++ flag and compatibility with newer llvm versions

- clang_delta/CMakeLists.txt
- clang_delta/RemoveUnusedFunction.cpp
- clang_delta/ReplaceDependentName.cpp
- clang_delta/ReplaceDependentTypedef.cpp
* Cherry-picking relevant commits from [cvise project](https://github.com/marxin/cvise/) for LLVM v18 compatibility
* NOTE: change to `clang_delta/CMakeLists.txt` required because I was getting:
```console
pramod@perfeng:~/repos/external/creduce/build/clang_delta$ /usr/bin/c++  -fno-rtti -fno-strict-aliasing -Wall -Wextra -Wno-long-long -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility-inlines-hidden -rdynamic CMakeFiles/clang_delta.dir/AggregateToScalar.cpp.o CMakeFiles/clang_delta.dir/BinOpSimplification.cpp.o CMakeFiles/clang_delta.dir/CallExprToValue.cpp.o CMakeFiles/clang_delta.dir/ClangDelta.cpp.o CMakeFiles/clang_delta.dir/ClassTemplateToClass.cpp.o CMakeFiles/clang_delta.dir/CombineGlobalVarDecl.cpp.o CMakeFiles/clang_delta.dir/CombineLocalVarDecl.cpp.o …
```
> Compatibility with LLVM 18: backport fixes from cvise

- clang_delta/CommonRenameClassRewriteVisitor.h
- clang_delta/RemoveNamespace.cpp
https://github.com/llvm/llvm-project/pull/91393 removed `ClassTemplateSpecializationDecl::getTypeAsWritten`. This was used to get the `SourceLocation` for the name of a `ClassTemplatePartialSpecializationDecl` in a few places, which is the same `SourceLocation` returned by `Decl::getLocation`. This fix should be backwards compatible. 
The removal of `getTypeAsWritten` also means that there no longer exists a `TemplateSpecializationTypeLoc` to be traversed by `RecursiveASTVisitor`, so this PR also includes a commit which ensures that explicit specializations/instantiations are correctly renamed.
See also https://github.com/marxin/cvise/issues/142.
> Remove uses of ClassTemplateSpecializationDecl::getTypeAsWritten
